apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "nodemanage.openshift.io/v1",
          "kind": "NodeLabels",
          "metadata": {
            "name": "nodelabels-sample"
          },
          "spec": {
            "labelGroup": [
              {
                "count": 1,
                "labels": {
                  "new": "1"
                }
              }
            ],
            "mode": "all",
            "nodeSelectorLabels": {
              "node-role.kubernetes.io/worker": ""
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.2.0
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: node-manage-operator.v0.2.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NodeLabels is the Schema for the nodelabels API
      displayName: Node Labels
      kind: NodeLabels
      name: nodelabels.nodemanage.openshift.io
      version: v1
  description: An operator to manage node's properties
  displayName: Node Manage Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - nodes
          verbs:
          - create
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - nodemanage.openshift.io
          resources:
          - nodelabels
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - nodemanage.openshift.io
          resources:
          - nodelabels/status
          verbs:
          - get
          - patch
          - update
        serviceAccountName: default
      deployments:
      - name: node-manage-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
                example-cnf-type: node-manage-operator
            spec:
              containers:
              - args:
                - --enable-leader-election
                command:
                - /manager
                image: quay.io/rh-nfv-int/node-manage-operator:v0.2.0
                imagePullPolicy: Always
                name: manager
                resources:
                  limits:
                    cpu: 100m
                    memory: 30Mi
                  requests:
                    cpu: 100m
                    memory: 20Mi
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - configmaps/status
          verbs:
          - get
          - update
          - patch
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: default
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - node
  - manage
  links:
  - name: Node Manage Operator
    url: https://node-manage-operator.domain
  maintainers:
  - email: skramaja@redhat.com
    name: Saravanan KR
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.2.0
