# permissions for end users to view nodelabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodelabels-viewer-role
rules:
- apiGroups:
  - nodemanage.openshift.io
  resources:
  - nodelabels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nodemanage.openshift.io
  resources:
  - nodelabels/status
  verbs:
  - get
