# permissions for end users to edit nodelabels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodelabels-editor-role
rules:
- apiGroups:
  - nodemanage.openshift.io
  resources:
  - nodelabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - nodemanage.openshift.io
  resources:
  - nodelabels/status
  verbs:
  - get
