apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.0.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v2
  name: node-manage-operator.vX.Y.Z
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: NodeLabels is the Schema for the nodelabels API
      displayName: Node Labels
      kind: NodeLabels
      name: nodelabels.nodemanage.openshift.io
      version: v1
  description: An operator to manage node's properties
  displayName: Node Manage Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - node
  - manage
  links:
  - name: Node Manage Operator
    url: https://node-manage-operator.domain
  maintainers:
  - email: skramaja@redhat.com
    name: Saravanan KR
  maturity: alpha
  provider:
    name: Red Hat
  version: 0.0.0
